### ISSUE TITLE
DB wrong format

### ISSUE THREAD

**Issue by nabat** [vintoniak/abills#3]
CREATE TABLE `user_inform` (
  `user_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_name` varchar(45) NOT NULL DEFAULT 'name',
  `user_address` varchar(45) NOT NULL DEFAULT 'address',
  `user_email` varchar(45) NOT NULL DEFAULT 'email',
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

1. don't use  lexical defaults
2. user_id ->  id best way fro Primary key

**Comment by nabat** [comment]
table without comments

**Comment by vintoniak** [comment]
fixed
